[build]
builder = "nixpacks"

[deploy]
startCommand = "python app.py"

[http]
port = 8080
healthcheckPath = "/"

[[services]]
name = "bot"
[services.ports]
port = 8080
protocol = "http"

[environments.production.vars]
BOT_TOKEN = "8240746309:AAEqhznhHLgSd2K0QMpmdBQHMHIyJNdrYG8"